#! /bin/bash
my_array=(qq mm kk ll)

read -p "value:" search_value

#get index of col
for i in "${!my_array[@]}"
do
if [[ "${my_array[$i]}" = "$search_value" ]]
then
			var=$i
                         
			#echo "Index of $search_value is: $i"
                         break  # Exit loop once value is found
fi
done

echo "$var"
